mongo_uri: mongodb://mongodb:27017
model_path: /app/models/bert_preference_model
vectors_path: /app/models/user_vectors.pkl
alpha: 0.01
weights:
  - 0.3  # ingredient_similarity
  - 0.3  # price_proximity
  - 0.2  # rating
  - 0.2  # sentiment
lambda_mmr: 0.7