services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog
    healthcheck:
      test: ["CMD-SHELL", "zookeeper-shell localhost:2181 ls / | grep zookeeper"]
      interval: 10s
      timeout: 5s
      retries: 10
    mem_limit: 512m
    networks:
      - leggy-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 2147483647
      KAFKA_REPLICA_FETCH_MAX_BYTES: 2147483647
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 10
    mem_limit: 768m
    networks:
      - leggy-network

  mongodb:
    image: mongo:6.0
    container_name: mongo-recommender
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: legy
      MONGO_INITDB_ROOT_PASSWORD: legy123
      MONGO_INITDB_DATABASE: leggydb
    command: ["mongod", "--wiredTigerCacheSizeGB=0.25"]
    healthcheck:
      test: ["CMD-SHELL", "mongo --host localhost --port 27017 --username legy --password legy123 --authenticationDatabase admin --eval 'db.adminCommand(\"ping\")'"]
      interval: 10s
      timeout: 15s
      retries: 20
      start_period: 30s
    mem_limit: 1g
    networks:
      - mongo-network

  recommender:
    build: .
    container_name: recommender
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://legy:legy123@mongodb:27017/leggydb
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    mem_limit: 1.5g
    networks:
      - leggy-network
      - mongo-network

networks:
  leggy-network:
    driver: bridge
  mongo-network:
    driver: bridge

volumes:
  mongo-data:
  kafka-data:
  zookeeper-data:
  zookeeper-datalog: